default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost

development:
  <<: *default
  database: stockmanage_development
  username: stockmanage
  password: 12345678

test:
  <<: *default
  database: stockmanage_test
  username: stockmanage
  password: 12345678

production:
  <<: *default
  database: stockmanage_production
  username: stockmanage
  password: <%= ENV['STOCKMANAGE_DATABASE_PASSWORD'] %>
